<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AINWZ.Infrastructure\AINWZ.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\Auth\Dto\" />
    <Folder Include="Contracts\Users\Dto\" />
  </ItemGroup>

</Project>
